---
dex:
  enabled: false
controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

server:
  metrics:
    enabled: true
  extraArgs:
#    - --insecure
    - --disable-auth
  ingress:
    enabled: true
    hosts:
      - argocd.127.0.0.1.nip.io

redis:
  metrics:
    enabled: true

