---
dex:
  enabled: false
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
repoServer:
  metrics:
    serviceMonitor:
      enabled: true
server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  extraArgs:
    - "--insecure"
  ingress:
    enabled: true
    hosts:
      - argocd.127.0.0.1.nip.io

redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
