---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keptn-nats
  namespace: argocd
spec:
  destination:
    namespace: keptn
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: system-keptn
  source:
    # https://github.com/nats-io/k8s/tree/main/helm/charts/nats
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts
    targetRevision: 0.17.4
    helm:
      values: |
        # enable monitoring
        exporter:
          enabled: true
          serviceMonitor:
            enabled: true
        # fix for name logic (because: bumped version or argo-cd rendering)
        nameOverride: keptn-nats-cluster
        # values from keptn chart
        nats.cluster.replicas: 3
        natsbox:
          enabled: false
        reloader:
          enabled: false
