---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keptn-mongodb
  namespace: argocd
spec:
  destination:
    namespace: keptn
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: system-keptn
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.1.5
    helm:
      releaseName: mongo
      values: |
        enabled: true
        host: mongodb:27017
        architecture: standalone
        service:
          nameOverride: 'mongo'
          port: 27017
        auth:
          database: 'keptn'
          existingSecret: 'mongodb-credentials' # If the password and rootPassword values below are used, remove this field.
          username: 'keptn'
          password: null
          rootUser: 'admin'
          rootPassword: null
          bridgeAuthDatabase: 'keptn'
        external:
          connectionString:
