---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keptn-gitops-operator
  namespace: argocd
spec:
  destination:
    namespace: keptn
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: system-keptn
  source:
    repoURL: https://github.com/czhujer/keptn-gitops-operator.git
    targetRevision: fix-charts-version
    path: charts/keptn-gitops
    helm:
      values: |
        global:
          rsaSecret:
            privateBase64: "xxx"
        keptn-operator:
          image: keptnsandbox/gitops-keptn-operator:0.1.0-pre.3
        gitops-operator:
          image: keptnsandbox/gitops-gitops-operator:0.1.0-pre.3
        promotion-service:
          image: docker.io/keptnsandbox/gitops-promotion-service:0.1.0-pre.3
