{{- if .Values.serviceMonitor.enabled }}
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  labels:
    app: helloservice
{{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
{{- end }}
  name: helloservice-service-monitor
{{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
{{- else }}
  namespace: {{ .Release.Namespace }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: helloservice
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  {{- if .Values.serviceMonitor.secure }}
    scheme: https
    tlsConfig:
      {{- toYaml .Values.serviceMonitor.tlsConfig | nindent 8 }}
    {{- end }}
{{- end }}
